// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCizsWbmmn1_NrQZJPRlc5SQwDw8W1Mfkg',
    appId: '1:211341917138:web:71aaf32e63cdfdbd0c260b',
    messagingSenderId: '211341917138',
    projectId: 'echo-app-3e6e3',
    authDomain: 'echo-app-3e6e3.firebaseapp.com',
    storageBucket: 'echo-app-3e6e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4W1xVWP-L2Dwrm-Erb_MH2qUcfv2h6_g',
    appId: '1:211341917138:android:ce5f2590876868620c260b',
    messagingSenderId: '211341917138',
    projectId: 'echo-app-3e6e3',
    storageBucket: 'echo-app-3e6e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4x0SX9f5uP7qptBCnDMw0_PeIjvCQTkA',
    appId: '1:211341917138:ios:a0e8863336b20f450c260b',
    messagingSenderId: '211341917138',
    projectId: 'echo-app-3e6e3',
    storageBucket: 'echo-app-3e6e3.appspot.com',
    iosClientId: '211341917138-3shao0urstfen5gglr4kuktthe8nq9qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.echoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4x0SX9f5uP7qptBCnDMw0_PeIjvCQTkA',
    appId: '1:211341917138:ios:f923b44b18952aad0c260b',
    messagingSenderId: '211341917138',
    projectId: 'echo-app-3e6e3',
    storageBucket: 'echo-app-3e6e3.appspot.com',
    iosClientId: '211341917138-9vpt9vp5o44cnpvfs5lo186f8plud8i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.echoApp.RunnerTests',
  );
}
